-- MySQL Script generated by MySQL Workbench
-- Wed Nov  8 12:32:51 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema soyeduca_sereyd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema soyeduca_sereyd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `soyeduca_sereyd` DEFAULT CHARACTER SET utf8 ;
USE `soyeduca_sereyd` ;

-- -----------------------------------------------------
-- Table `soyeduca_sereyd`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soyeduca_sereyd`.`user` (
  `id_user` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(200) NULL DEFAULT NULL COMMENT '	',
  `password` VARCHAR(200) NULL DEFAULT NULL,
  `id_facebook` VARCHAR(200) NULL DEFAULT NULL,
  `name` VARCHAR(200) NULL DEFAULT NULL,
  `date_creation` DATE NULL DEFAULT NULL,
  `image` VARCHAR(300) NULL DEFAULT NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `id_facebook_UNIQUE` (`id_facebook` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2079
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `soyeduca_sereyd`.`group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soyeduca_sereyd`.`group` (
  `id_group` INT(11) NOT NULL AUTO_INCREMENT,
  `school` VARCHAR(45) NOT NULL,
  `grade` VARCHAR(45) NOT NULL,
  `group_number` VARCHAR(45) NOT NULL,
  `period` VARCHAR(45) NOT NULL,
  `id_user` INT(11) NOT NULL,
  PRIMARY KEY (`id_group`, `id_user`),
  INDEX `fk_group_user_idx` (`id_user` ASC),
  CONSTRAINT `fk_group_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `soyeduca_sereyd`.`user` (`id_user`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 954
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `soyeduca_sereyd`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soyeduca_sereyd`.`student` (
  `id_student` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  `lastname` VARCHAR(250) NOT NULL,
  `birthday` DATE NOT NULL,
  `gender` TINYINT(1) NOT NULL DEFAULT '0',
  `image` VARCHAR(150) NOT NULL,
  `emergency_contact` VARCHAR(200) NOT NULL,
  `id_group` INT(11) NOT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `password` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id_student`, `id_group`),
  INDEX `fk_student_group1_idx` (`id_group` ASC),
  CONSTRAINT `fk_student_group1`
    FOREIGN KEY (`id_group`)
    REFERENCES `soyeduca_sereyd`.`group` (`id_group`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 1145
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `soyeduca_sereyd`.`attendance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soyeduca_sereyd`.`attendance` (
  `id_attendance` INT(11) NOT NULL AUTO_INCREMENT,
  `date_attendance` DATE NULL DEFAULT NULL,
  `value` TINYINT(1) NULL DEFAULT NULL,
  `id_student` INT(11) NOT NULL,
  `id_group` INT(11) NOT NULL,
  PRIMARY KEY (`id_attendance`, `id_student`, `id_group`),
  INDEX `fk_attendance_student1_idx` (`id_student` ASC, `id_group` ASC),
  CONSTRAINT `fk_attendance_student1`
    FOREIGN KEY (`id_student` , `id_group`)
    REFERENCES `soyeduca_sereyd`.`student` (`id_student` , `id_group`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 1642
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `soyeduca_sereyd`.`behavior`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soyeduca_sereyd`.`behavior` (
  `id_behavior` INT(11) NOT NULL AUTO_INCREMENT,
  `value` INT(11) NULL DEFAULT NULL,
  `date_behavior` DATE NULL DEFAULT NULL,
  `id_student` INT(11) NOT NULL,
  `id_group` INT(11) NOT NULL,
  PRIMARY KEY (`id_behavior`, `id_student`, `id_group`),
  INDEX `fk_behavior_student1_idx` (`id_student` ASC, `id_group` ASC),
  CONSTRAINT `fk_behavior_student1`
    FOREIGN KEY (`id_student` , `id_group`)
    REFERENCES `soyeduca_sereyd`.`student` (`id_student` , `id_group`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 1642
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `soyeduca_sereyd`.`category_resource`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soyeduca_sereyd`.`category_resource` (
  `id_category_resource` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id_category_resource`))
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `soyeduca_sereyd`.`cooperation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soyeduca_sereyd`.`cooperation` (
  `id_cooperation` INT(11) NOT NULL AUTO_INCREMENT,
  `concept` VARCHAR(200) NOT NULL,
  `description` TEXT NOT NULL,
  `amount` INT(11) NOT NULL,
  `id_group` INT(11) NOT NULL,
  PRIMARY KEY (`id_cooperation`, `id_group`),
  INDEX `fk_contribution_group1_idx` (`id_group` ASC),
  CONSTRAINT `fk_contribution_group1`
    FOREIGN KEY (`id_group`)
    REFERENCES `soyeduca_sereyd`.`group` (`id_group`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 35
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `soyeduca_sereyd`.`diagnostic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soyeduca_sereyd`.`diagnostic` (
  `id_diagnostic` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `active` INT(11) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id_diagnostic`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `soyeduca_sereyd`.`planification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soyeduca_sereyd`.`planification` (
  `id_planification` INT(11) NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(150) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(600) NOT NULL,
  `image` VARCHAR(150) NOT NULL,
  `url_word` VARCHAR(200) NOT NULL,
  `preview` VARCHAR(200) NOT NULL,
  `formative_field` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id_planification`))
ENGINE = InnoDB
AUTO_INCREMENT = 71
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `soyeduca_sereyd`.`evaluation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soyeduca_sereyd`.`evaluation` (
  `id_evaluation` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `id_planification` INT(11) NOT NULL,
  PRIMARY KEY (`id_evaluation`, `id_planification`),
  INDEX `fk_evaluation_planification_idx` (`id_planification` ASC),
  CONSTRAINT `fk_evaluation_planification`
    FOREIGN KEY (`id_planification`)
    REFERENCES `soyeduca_sereyd`.`planification` (`id_planification`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 71
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `soyeduca_sereyd`.`group_diagnostic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soyeduca_sereyd`.`group_diagnostic` (
  `id_diagnostic` INT(11) NOT NULL,
  `id_group` INT(11) NOT NULL,
  `id_group_diagnostic` INT(11) NOT NULL AUTO_INCREMENT,
  `completed` TINYINT(1) NOT NULL DEFAULT '0',
  `created_at` DATE NOT NULL,
  PRIMARY KEY (`id_group_diagnostic`),
  INDEX `fk_group_diagnostic_group1_idx` (`id_group` ASC),
  INDEX `fk_group_diagnostic_diagnostic1` (`id_diagnostic` ASC),
  CONSTRAINT `fk_group_diagnostic_diagnostic1`
    FOREIGN KEY (`id_diagnostic`)
    REFERENCES `soyeduca_sereyd`.`diagnostic` (`id_diagnostic`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_group_diagnostic_group1`
    FOREIGN KEY (`id_group`)
    REFERENCES `soyeduca_sereyd`.`group` (`id_group`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 147
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `soyeduca_sereyd`.`group_evaluation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soyeduca_sereyd`.`group_evaluation` (
  `id_group_evaluation` INT(11) NOT NULL AUTO_INCREMENT,
  `completed` TINYINT(1) NOT NULL DEFAULT '0',
  `id_evaluation` INT(11) NOT NULL,
  `id_group` INT(11) NOT NULL,
  `created_at` DATE NOT NULL,
  PRIMARY KEY (`id_group_evaluation`),
  INDEX `fk_group_evaluation_evaluation1_idx` (`id_evaluation` ASC),
  INDEX `fk_group_evaluation_group1_idx` (`id_group` ASC),
  CONSTRAINT `fk_group_evaluation_evaluation1`
    FOREIGN KEY (`id_evaluation`)
    REFERENCES `soyeduca_sereyd`.`evaluation` (`id_evaluation`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_group_evaluation_group1`
    FOREIGN KEY (`id_group`)
    REFERENCES `soyeduca_sereyd`.`group` (`id_group`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 108
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `soyeduca_sereyd`.`homework`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soyeduca_sereyd`.`homework` (
  `id_homework` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  `description` TEXT NOT NULL,
  `deadline` DATE NOT NULL,
  `id_group` INT(11) NOT NULL,
  PRIMARY KEY (`id_homework`, `id_group`),
  INDEX `fk_homework_group1_idx` (`id_group` ASC),
  CONSTRAINT `fk_homework_group1`
    FOREIGN KEY (`id_group`)
    REFERENCES `soyeduca_sereyd`.`group` (`id_group`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 42
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `soyeduca_sereyd`.`notice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soyeduca_sereyd`.`notice` (
  `id_notice` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  `description` TEXT NOT NULL,
  `date` DATE NOT NULL,
  `time` TIME NOT NULL,
  `id_group` INT(11) NOT NULL,
  PRIMARY KEY (`id_notice`, `id_group`),
  INDEX `fk_notice_group1_idx` (`id_group` ASC),
  CONSTRAINT `fk_notice_group1`
    FOREIGN KEY (`id_group`)
    REFERENCES `soyeduca_sereyd`.`group` (`id_group`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `soyeduca_sereyd`.`pay`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soyeduca_sereyd`.`pay` (
  `id_pay` INT(11) NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `amount` DOUBLE NOT NULL,
  `description` VARCHAR(150) NOT NULL,
  `id_user` INT(11) NOT NULL,
  PRIMARY KEY (`id_pay`, `id_user`),
  INDEX `fk_pay_user_idx` (`id_user` ASC),
  CONSTRAINT `fk_pay_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `soyeduca_sereyd`.`user` (`id_user`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 48
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `soyeduca_sereyd`.`payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soyeduca_sereyd`.`payment` (
  `id_payment` INT(11) NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `planification_count` INT(11) NOT NULL,
  `resource_count` INT(11) NOT NULL DEFAULT '20',
  `id_user` INT(11) NOT NULL,
  `trial` TINYINT(1) NOT NULL DEFAULT '0',
  `month` INT(11) NOT NULL DEFAULT '0',
  `annual` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id_payment`, `id_user`),
  INDEX `fk_payment_user1_idx` (`id_user` ASC),
  CONSTRAINT `fk_payment_user1`
    FOREIGN KEY (`id_user`)
    REFERENCES `soyeduca_sereyd`.`user` (`id_user`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 1996
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `soyeduca_sereyd`.`planification_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soyeduca_sereyd`.`planification_user` (
  `id_user` INT(11) NOT NULL,
  `id_planification` INT(11) NOT NULL,
  PRIMARY KEY (`id_user`, `id_planification`),
  INDEX `fk_planification_user_planification1_idx` (`id_planification` ASC),
  CONSTRAINT `fk_planification_user_planification1`
    FOREIGN KEY (`id_planification`)
    REFERENCES `soyeduca_sereyd`.`planification` (`id_planification`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_planification_user_user1`
    FOREIGN KEY (`id_user`)
    REFERENCES `soyeduca_sereyd`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `soyeduca_sereyd`.`test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soyeduca_sereyd`.`test` (
  `id_test` INT(11) NOT NULL AUTO_INCREMENT,
  `id_diagnostic` INT(11) NOT NULL,
  `name` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id_test`, `id_diagnostic`),
  INDEX `fk_test_diagnostic1_idx` (`id_diagnostic` ASC),
  CONSTRAINT `fk_test_diagnostic1`
    FOREIGN KEY (`id_diagnostic`)
    REFERENCES `soyeduca_sereyd`.`diagnostic` (`id_diagnostic`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 25
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `soyeduca_sereyd`.`question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soyeduca_sereyd`.`question` (
  `id_question` INT(11) NOT NULL AUTO_INCREMENT,
  `question` VARCHAR(300) NOT NULL,
  `id_test` INT(11) NOT NULL,
  PRIMARY KEY (`id_question`, `id_test`),
  INDEX `fk_question_test1_idx` (`id_test` ASC),
  CONSTRAINT `fk_question_test1`
    FOREIGN KEY (`id_test`)
    REFERENCES `soyeduca_sereyd`.`test` (`id_test`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 279
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `soyeduca_sereyd`.`question_evaluation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soyeduca_sereyd`.`question_evaluation` (
  `id_question_evaluation` INT(11) NOT NULL AUTO_INCREMENT,
  `question` VARCHAR(150) NOT NULL,
  `id_evaluation` INT(11) NOT NULL,
  PRIMARY KEY (`id_question_evaluation`, `id_evaluation`),
  INDEX `fk_question_evaluation_evaluation1_idx` (`id_evaluation` ASC),
  CONSTRAINT `fk_question_evaluation_evaluation1`
    FOREIGN KEY (`id_evaluation`)
    REFERENCES `soyeduca_sereyd`.`evaluation` (`id_evaluation`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 256
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `soyeduca_sereyd`.`question_evaluation_student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soyeduca_sereyd`.`question_evaluation_student` (
  `answer` INT(11) NOT NULL,
  `id_student` INT(11) NOT NULL,
  `id_question_evaluation` INT(11) NOT NULL,
  `id_group_evaluation` INT(11) NOT NULL,
  INDEX `fk_question_evaluation_student_student1_idx` (`id_student` ASC),
  INDEX `fk_question_evaluation_student_question_evaluation1_idx` (`id_question_evaluation` ASC),
  CONSTRAINT `fk_question_evaluation_student_question_evaluation1`
    FOREIGN KEY (`id_question_evaluation`)
    REFERENCES `soyeduca_sereyd`.`question_evaluation` (`id_question_evaluation`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_question_evaluation_student_student1`
    FOREIGN KEY (`id_student`)
    REFERENCES `soyeduca_sereyd`.`student` (`id_student`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `soyeduca_sereyd`.`question_student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soyeduca_sereyd`.`question_student` (
  `answer` INT(11) NOT NULL,
  `id_question` INT(11) NOT NULL,
  `id_student` INT(11) NOT NULL,
  `id_group_diagnostic` INT(11) NOT NULL,
  `id_test` INT(11) NOT NULL,
  INDEX `fk_question_student_student1_idx` (`id_student` ASC),
  INDEX `fk_question_student_question1` (`id_question` ASC),
  CONSTRAINT `fk_question_student_question1`
    FOREIGN KEY (`id_question`)
    REFERENCES `soyeduca_sereyd`.`question` (`id_question`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_question_student_student1`
    FOREIGN KEY (`id_student`)
    REFERENCES `soyeduca_sereyd`.`student` (`id_student`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `soyeduca_sereyd`.`resource`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soyeduca_sereyd`.`resource` (
  `id_resource` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `url` VARCHAR(200) NOT NULL,
  `id_category_resource` INT(11) NOT NULL,
  PRIMARY KEY (`id_resource`, `id_category_resource`),
  INDEX `fk_resource_category_resource1_idx` (`id_category_resource` ASC),
  CONSTRAINT `fk_resource_category_resource1`
    FOREIGN KEY (`id_category_resource`)
    REFERENCES `soyeduca_sereyd`.`category_resource` (`id_category_resource`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 199
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `soyeduca_sereyd`.`user_resource`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soyeduca_sereyd`.`user_resource` (
  `id_user_resource` INT(11) NOT NULL AUTO_INCREMENT,
  `id_user` INT(11) NOT NULL,
  `id_resource` INT(11) NOT NULL,
  PRIMARY KEY (`id_user_resource`),
  INDEX `fk_user_resource_user1_idx` (`id_user` ASC),
  INDEX `fk_user_resource_resource1_idx` (`id_resource` ASC),
  CONSTRAINT `fk_user_resource_resource1`
    FOREIGN KEY (`id_resource`)
    REFERENCES `soyeduca_sereyd`.`resource` (`id_resource`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_resource_user1`
    FOREIGN KEY (`id_user`)
    REFERENCES `soyeduca_sereyd`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 952
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
